{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "d69f9cd6-67b5-464e-b059-6400bd31ceef",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "os.environ['CUDA_VISIBLE_DEVICES']='4'"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "44c4d182-65b9-4cba-9e8d-8972d55337b3",
   "metadata": {},
   "source": [
    "## 패키지 설치 및 Drive 연결"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "d5b6a987-b13a-4d16-841e-fd757152444a",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: PyDrive in ./.local/lib/python3.10/site-packages (1.3.1)\n",
      "Requirement already satisfied: google-api-python-client>=1.2 in ./.local/lib/python3.10/site-packages (from PyDrive) (2.79.0)\n",
      "Requirement already satisfied: oauth2client>=4.0.0 in ./.local/lib/python3.10/site-packages (from PyDrive) (4.1.3)\n",
      "Requirement already satisfied: PyYAML>=3.0 in /opt/tljh/user/lib/python3.10/site-packages (from PyDrive) (6.0.1)\n",
      "Requirement already satisfied: httplib2<1dev,>=0.15.0 in ./.local/lib/python3.10/site-packages (from google-api-python-client>=1.2->PyDrive) (0.22.0)\n",
      "Requirement already satisfied: google-auth<3.0.0dev,>=1.19.0 in ./.local/lib/python3.10/site-packages (from google-api-python-client>=1.2->PyDrive) (2.16.1)\n",
      "Requirement already satisfied: google-auth-httplib2>=0.1.0 in ./.local/lib/python3.10/site-packages (from google-api-python-client>=1.2->PyDrive) (0.1.0)\n",
      "Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 in ./.local/lib/python3.10/site-packages (from google-api-python-client>=1.2->PyDrive) (2.11.0)\n",
      "Requirement already satisfied: uritemplate<5,>=3.0.1 in ./.local/lib/python3.10/site-packages (from google-api-python-client>=1.2->PyDrive) (4.1.1)\n",
      "Requirement already satisfied: pyasn1>=0.1.7 in ./.local/lib/python3.10/site-packages (from oauth2client>=4.0.0->PyDrive) (0.6.1)\n",
      "Requirement already satisfied: pyasn1-modules>=0.0.5 in ./.local/lib/python3.10/site-packages (from oauth2client>=4.0.0->PyDrive) (0.4.1)\n",
      "Requirement already satisfied: rsa>=3.1.4 in ./.local/lib/python3.10/site-packages (from oauth2client>=4.0.0->PyDrive) (4.9)\n",
      "Requirement already satisfied: six>=1.6.1 in /opt/tljh/user/lib/python3.10/site-packages (from oauth2client>=4.0.0->PyDrive) (1.16.0)\n",
      "Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.56.2 in ./.local/lib/python3.10/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client>=1.2->PyDrive) (1.58.0)\n",
      "Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5 in ./.local/lib/python3.10/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client>=1.2->PyDrive) (4.25.4)\n",
      "Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /opt/tljh/user/lib/python3.10/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client>=1.2->PyDrive) (2.32.3)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in ./.local/lib/python3.10/site-packages (from google-auth<3.0.0dev,>=1.19.0->google-api-python-client>=1.2->PyDrive) (5.5.0)\n",
      "Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in ./.local/lib/python3.10/site-packages (from httplib2<1dev,>=0.15.0->google-api-python-client>=1.2->PyDrive) (3.1.4)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /opt/tljh/user/lib/python3.10/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client>=1.2->PyDrive) (3.1.0)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /opt/tljh/user/lib/python3.10/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client>=1.2->PyDrive) (3.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/tljh/user/lib/python3.10/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client>=1.2->PyDrive) (1.26.15)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /opt/tljh/user/lib/python3.10/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client>=1.2->PyDrive) (2024.6.2)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mLooking in indexes: https://download.pytorch.org/whl/cu118\n",
      "Collecting torch\n",
      "  Using cached https://download.pytorch.org/whl/cu118/torch-2.4.1%2Bcu118-cp310-cp310-linux_x86_64.whl (857.6 MB)\n",
      "Collecting torchvision\n",
      "  Using cached https://download.pytorch.org/whl/cu118/torchvision-0.19.1%2Bcu118-cp310-cp310-linux_x86_64.whl (6.3 MB)\n",
      "Collecting filelock (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/filelock-3.13.1-py3-none-any.whl (11 kB)\n",
      "Collecting typing-extensions>=4.8.0 (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/typing_extensions-4.9.0-py3-none-any.whl (32 kB)\n",
      "Collecting sympy (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/sympy-1.12-py3-none-any.whl (5.7 MB)\n",
      "Collecting networkx (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/networkx-3.2.1-py3-none-any.whl (1.6 MB)\n",
      "Collecting jinja2 (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/Jinja2-3.1.3-py3-none-any.whl (133 kB)\n",
      "Collecting fsspec (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/fsspec-2024.2.0-py3-none-any.whl (170 kB)\n",
      "Collecting nvidia-cuda-nvrtc-cu11==11.8.89 (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/cu118/nvidia_cuda_nvrtc_cu11-11.8.89-py3-none-manylinux1_x86_64.whl (23.2 MB)\n",
      "Collecting nvidia-cuda-runtime-cu11==11.8.89 (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/cu118/nvidia_cuda_runtime_cu11-11.8.89-py3-none-manylinux1_x86_64.whl (875 kB)\n",
      "Collecting nvidia-cuda-cupti-cu11==11.8.87 (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/cu118/nvidia_cuda_cupti_cu11-11.8.87-py3-none-manylinux1_x86_64.whl (13.1 MB)\n",
      "Collecting nvidia-cudnn-cu11==9.1.0.70 (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/cu118/nvidia_cudnn_cu11-9.1.0.70-py3-none-manylinux2014_x86_64.whl (663.9 MB)\n",
      "Collecting nvidia-cublas-cu11==11.11.3.6 (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/cu118/nvidia_cublas_cu11-11.11.3.6-py3-none-manylinux1_x86_64.whl (417.9 MB)\n",
      "Collecting nvidia-cufft-cu11==10.9.0.58 (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/cu118/nvidia_cufft_cu11-10.9.0.58-py3-none-manylinux1_x86_64.whl (168.4 MB)\n",
      "Collecting nvidia-curand-cu11==10.3.0.86 (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/cu118/nvidia_curand_cu11-10.3.0.86-py3-none-manylinux1_x86_64.whl (58.1 MB)\n",
      "Collecting nvidia-cusolver-cu11==11.4.1.48 (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/cu118/nvidia_cusolver_cu11-11.4.1.48-py3-none-manylinux1_x86_64.whl (128.2 MB)\n",
      "Collecting nvidia-cusparse-cu11==11.7.5.86 (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/cu118/nvidia_cusparse_cu11-11.7.5.86-py3-none-manylinux1_x86_64.whl (204.1 MB)\n",
      "Collecting nvidia-nccl-cu11==2.20.5 (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/cu118/nvidia_nccl_cu11-2.20.5-py3-none-manylinux2014_x86_64.whl (142.9 MB)\n",
      "Collecting nvidia-nvtx-cu11==11.8.86 (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/cu118/nvidia_nvtx_cu11-11.8.86-py3-none-manylinux1_x86_64.whl (99 kB)\n",
      "Collecting triton==3.0.0 (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/triton-3.0.0-1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (209.4 MB)\n",
      "Collecting numpy (from torchvision)\n",
      "  Using cached https://download.pytorch.org/whl/numpy-1.26.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)\n",
      "Collecting pillow!=8.3.*,>=5.3.0 (from torchvision)\n",
      "  Using cached https://download.pytorch.org/whl/pillow-10.2.0-cp310-cp310-manylinux_2_28_x86_64.whl (4.5 MB)\n",
      "Collecting MarkupSafe>=2.0 (from jinja2->torch)\n",
      "  Using cached https://download.pytorch.org/whl/MarkupSafe-2.1.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)\n",
      "Collecting mpmath>=0.19 (from sympy->torch)\n",
      "  Using cached https://download.pytorch.org/whl/mpmath-1.3.0-py3-none-any.whl (536 kB)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mInstalling collected packages: mpmath, typing-extensions, sympy, pillow, nvidia-nvtx-cu11, nvidia-nccl-cu11, nvidia-cusparse-cu11, nvidia-curand-cu11, nvidia-cufft-cu11, nvidia-cuda-runtime-cu11, nvidia-cuda-nvrtc-cu11, nvidia-cuda-cupti-cu11, nvidia-cublas-cu11, numpy, networkx, MarkupSafe, fsspec, filelock, triton, nvidia-cusolver-cu11, nvidia-cudnn-cu11, jinja2, torch, torchvision\n",
      "  Attempting uninstall: mpmath\n",
      "    Found existing installation: mpmath 1.3.0\n",
      "    Uninstalling mpmath-1.3.0:\n",
      "      Successfully uninstalled mpmath-1.3.0\n",
      "  Attempting uninstall: typing-extensions\n",
      "    Found existing installation: typing_extensions 4.9.0\n",
      "    Uninstalling typing_extensions-4.9.0:\n",
      "      Successfully uninstalled typing_extensions-4.9.0\n",
      "  Attempting uninstall: sympy\n",
      "    Found existing installation: sympy 1.12\n",
      "    Uninstalling sympy-1.12:\n",
      "      Successfully uninstalled sympy-1.12\n",
      "\u001b[33m  WARNING: The script isympy is installed in '/home/j-j11a303/.local/bin' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\u001b[0m\u001b[33m\n",
      "\u001b[0m  Attempting uninstall: pillow\n",
      "    Found existing installation: pillow 10.2.0\n",
      "    Uninstalling pillow-10.2.0:\n",
      "      Successfully uninstalled pillow-10.2.0\n",
      "  Attempting uninstall: nvidia-nvtx-cu11\n",
      "    Found existing installation: nvidia-nvtx-cu11 11.8.86\n",
      "    Uninstalling nvidia-nvtx-cu11-11.8.86:\n",
      "      Successfully uninstalled nvidia-nvtx-cu11-11.8.86\n",
      "  Attempting uninstall: nvidia-nccl-cu11\n",
      "    Found existing installation: nvidia-nccl-cu11 2.20.5\n",
      "    Uninstalling nvidia-nccl-cu11-2.20.5:\n",
      "      Successfully uninstalled nvidia-nccl-cu11-2.20.5\n",
      "  Attempting uninstall: nvidia-cusparse-cu11\n",
      "    Found existing installation: nvidia-cusparse-cu11 11.7.5.86\n",
      "    Uninstalling nvidia-cusparse-cu11-11.7.5.86:\n",
      "      Successfully uninstalled nvidia-cusparse-cu11-11.7.5.86\n",
      "  Attempting uninstall: nvidia-curand-cu11\n",
      "    Found existing installation: nvidia-curand-cu11 10.3.0.86\n",
      "    Uninstalling nvidia-curand-cu11-10.3.0.86:\n",
      "      Successfully uninstalled nvidia-curand-cu11-10.3.0.86\n",
      "  Attempting uninstall: nvidia-cufft-cu11\n",
      "    Found existing installation: nvidia-cufft-cu11 10.9.0.58\n",
      "    Uninstalling nvidia-cufft-cu11-10.9.0.58:\n",
      "      Successfully uninstalled nvidia-cufft-cu11-10.9.0.58\n",
      "  Attempting uninstall: nvidia-cuda-runtime-cu11\n",
      "    Found existing installation: nvidia-cuda-runtime-cu11 11.8.89\n",
      "    Uninstalling nvidia-cuda-runtime-cu11-11.8.89:\n",
      "      Successfully uninstalled nvidia-cuda-runtime-cu11-11.8.89\n",
      "  Attempting uninstall: nvidia-cuda-nvrtc-cu11\n",
      "    Found existing installation: nvidia-cuda-nvrtc-cu11 11.8.89\n",
      "    Uninstalling nvidia-cuda-nvrtc-cu11-11.8.89:\n",
      "      Successfully uninstalled nvidia-cuda-nvrtc-cu11-11.8.89\n",
      "  Attempting uninstall: nvidia-cuda-cupti-cu11\n",
      "    Found existing installation: nvidia-cuda-cupti-cu11 11.8.87\n",
      "    Uninstalling nvidia-cuda-cupti-cu11-11.8.87:\n",
      "      Successfully uninstalled nvidia-cuda-cupti-cu11-11.8.87\n",
      "  Attempting uninstall: nvidia-cublas-cu11\n",
      "    Found existing installation: nvidia-cublas-cu11 11.11.3.6\n",
      "    Uninstalling nvidia-cublas-cu11-11.11.3.6:\n",
      "      Successfully uninstalled nvidia-cublas-cu11-11.11.3.6\n",
      "  Attempting uninstall: numpy\n",
      "    Found existing installation: numpy 1.26.3\n",
      "    Uninstalling numpy-1.26.3:\n",
      "      Successfully uninstalled numpy-1.26.3\n",
      "\u001b[33m  WARNING: The script f2py is installed in '/home/j-j11a303/.local/bin' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\u001b[0m\u001b[33m\n",
      "\u001b[0m  Attempting uninstall: networkx\n",
      "    Found existing installation: networkx 3.2.1\n",
      "    Uninstalling networkx-3.2.1:\n",
      "      Successfully uninstalled networkx-3.2.1\n",
      "  Attempting uninstall: MarkupSafe\n",
      "    Found existing installation: MarkupSafe 2.1.5\n",
      "    Uninstalling MarkupSafe-2.1.5:\n",
      "      Successfully uninstalled MarkupSafe-2.1.5\n",
      "  Attempting uninstall: fsspec\n",
      "    Found existing installation: fsspec 2024.2.0\n",
      "    Uninstalling fsspec-2024.2.0:\n",
      "      Successfully uninstalled fsspec-2024.2.0\n",
      "  Attempting uninstall: filelock\n",
      "    Found existing installation: filelock 3.13.1\n",
      "    Uninstalling filelock-3.13.1:\n",
      "      Successfully uninstalled filelock-3.13.1\n",
      "  Attempting uninstall: triton\n",
      "    Found existing installation: triton 3.0.0\n",
      "    Uninstalling triton-3.0.0:\n",
      "      Successfully uninstalled triton-3.0.0\n",
      "\u001b[33m  WARNING: The scripts proton and proton-viewer are installed in '/home/j-j11a303/.local/bin' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\u001b[0m\u001b[33m\n",
      "\u001b[0m  Attempting uninstall: nvidia-cusolver-cu11\n",
      "    Found existing installation: nvidia-cusolver-cu11 11.4.1.48\n",
      "    Uninstalling nvidia-cusolver-cu11-11.4.1.48:\n",
      "      Successfully uninstalled nvidia-cusolver-cu11-11.4.1.48\n",
      "  Attempting uninstall: nvidia-cudnn-cu11\n",
      "    Found existing installation: nvidia-cudnn-cu11 9.1.0.70\n",
      "    Uninstalling nvidia-cudnn-cu11-9.1.0.70:\n",
      "      Successfully uninstalled nvidia-cudnn-cu11-9.1.0.70\n",
      "  Attempting uninstall: jinja2\n",
      "    Found existing installation: Jinja2 3.1.3\n",
      "    Uninstalling Jinja2-3.1.3:\n",
      "      Successfully uninstalled Jinja2-3.1.3\n",
      "  Attempting uninstall: torch\n",
      "    Found existing installation: torch 2.4.1+cu118\n",
      "    Uninstalling torch-2.4.1+cu118:\n",
      "      Successfully uninstalled torch-2.4.1+cu118\n",
      "\u001b[33m  WARNING: The scripts convert-caffe2-to-onnx, convert-onnx-to-caffe2 and torchrun are installed in '/home/j-j11a303/.local/bin' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\u001b[0m\u001b[33m\n",
      "\u001b[0m  Attempting uninstall: torchvision\n",
      "    Found existing installation: torchvision 0.19.1+cu118\n",
      "    Uninstalling torchvision-0.19.1+cu118:\n",
      "      Successfully uninstalled torchvision-0.19.1+cu118\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mSuccessfully installed MarkupSafe-2.1.5 filelock-3.13.1 fsspec-2024.2.0 jinja2-3.1.3 mpmath-1.3.0 networkx-3.2.1 numpy-1.26.3 nvidia-cublas-cu11-11.11.3.6 nvidia-cuda-cupti-cu11-11.8.87 nvidia-cuda-nvrtc-cu11-11.8.89 nvidia-cuda-runtime-cu11-11.8.89 nvidia-cudnn-cu11-9.1.0.70 nvidia-cufft-cu11-10.9.0.58 nvidia-curand-cu11-10.3.0.86 nvidia-cusolver-cu11-11.4.1.48 nvidia-cusparse-cu11-11.7.5.86 nvidia-nccl-cu11-2.20.5 nvidia-nvtx-cu11-11.8.86 pillow-10.2.0 sympy-1.12 torch-2.4.1+cu118 torchvision-0.19.1+cu118 triton-3.0.0 typing-extensions-4.9.0\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: opencv-python in ./.local/lib/python3.10/site-packages (4.10.0.84)\n",
      "Requirement already satisfied: numpy>=1.21.2 in ./.local/lib/python3.10/site-packages (from opencv-python) (1.26.3)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: opencv-python-headless in ./.local/lib/python3.10/site-packages (4.10.0.84)\n",
      "Requirement already satisfied: numpy>=1.21.2 in ./.local/lib/python3.10/site-packages (from opencv-python-headless) (1.26.3)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: torchvision in ./.local/lib/python3.10/site-packages (0.19.1+cu118)\n",
      "Requirement already satisfied: numpy in ./.local/lib/python3.10/site-packages (from torchvision) (1.26.3)\n",
      "Requirement already satisfied: torch==2.4.1 in ./.local/lib/python3.10/site-packages (from torchvision) (2.4.1+cu118)\n",
      "Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in ./.local/lib/python3.10/site-packages (from torchvision) (10.2.0)\n",
      "Requirement already satisfied: filelock in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (3.13.1)\n",
      "Requirement already satisfied: typing-extensions>=4.8.0 in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (4.9.0)\n",
      "Requirement already satisfied: sympy in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (1.12)\n",
      "Requirement already satisfied: networkx in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (3.2.1)\n",
      "Requirement already satisfied: jinja2 in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (3.1.3)\n",
      "Requirement already satisfied: fsspec in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (2024.2.0)\n",
      "Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.8.89 in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (11.8.89)\n",
      "Requirement already satisfied: nvidia-cuda-runtime-cu11==11.8.89 in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (11.8.89)\n",
      "Requirement already satisfied: nvidia-cuda-cupti-cu11==11.8.87 in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (11.8.87)\n",
      "Requirement already satisfied: nvidia-cudnn-cu11==9.1.0.70 in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (9.1.0.70)\n",
      "Requirement already satisfied: nvidia-cublas-cu11==11.11.3.6 in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (11.11.3.6)\n",
      "Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (10.9.0.58)\n",
      "Requirement already satisfied: nvidia-curand-cu11==10.3.0.86 in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (10.3.0.86)\n",
      "Requirement already satisfied: nvidia-cusolver-cu11==11.4.1.48 in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (11.4.1.48)\n",
      "Requirement already satisfied: nvidia-cusparse-cu11==11.7.5.86 in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (11.7.5.86)\n",
      "Requirement already satisfied: nvidia-nccl-cu11==2.20.5 in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (2.20.5)\n",
      "Requirement already satisfied: nvidia-nvtx-cu11==11.8.86 in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (11.8.86)\n",
      "Requirement already satisfied: triton==3.0.0 in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (3.0.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in ./.local/lib/python3.10/site-packages (from jinja2->torch==2.4.1->torchvision) (2.1.5)\n",
      "Requirement already satisfied: mpmath>=0.19 in ./.local/lib/python3.10/site-packages (from sympy->torch==2.4.1->torchvision) (1.3.0)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: google-api-core==2.11.0 in ./.local/lib/python3.10/site-packages (2.11.0)\n",
      "Requirement already satisfied: google-api-python-client==2.79.0 in ./.local/lib/python3.10/site-packages (2.79.0)\n",
      "Requirement already satisfied: google-auth==2.16.1 in ./.local/lib/python3.10/site-packages (2.16.1)\n",
      "Requirement already satisfied: google-auth-httplib2==0.1.0 in ./.local/lib/python3.10/site-packages (0.1.0)\n",
      "Collecting google-auth-oauthlib==0.4.1\n",
      "  Using cached google_auth_oauthlib-0.4.1-py2.py3-none-any.whl.metadata (2.4 kB)\n",
      "Requirement already satisfied: googleapis-common-protos==1.58.0 in ./.local/lib/python3.10/site-packages (1.58.0)\n",
      "Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5 in ./.local/lib/python3.10/site-packages (from google-api-core==2.11.0) (4.25.4)\n",
      "Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /opt/tljh/user/lib/python3.10/site-packages (from google-api-core==2.11.0) (2.32.3)\n",
      "Requirement already satisfied: httplib2<1dev,>=0.15.0 in ./.local/lib/python3.10/site-packages (from google-api-python-client==2.79.0) (0.22.0)\n",
      "Requirement already satisfied: uritemplate<5,>=3.0.1 in ./.local/lib/python3.10/site-packages (from google-api-python-client==2.79.0) (4.1.1)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in ./.local/lib/python3.10/site-packages (from google-auth==2.16.1) (5.5.0)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in ./.local/lib/python3.10/site-packages (from google-auth==2.16.1) (0.4.1)\n",
      "Requirement already satisfied: six>=1.9.0 in /opt/tljh/user/lib/python3.10/site-packages (from google-auth==2.16.1) (1.16.0)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in ./.local/lib/python3.10/site-packages (from google-auth==2.16.1) (4.9)\n",
      "Requirement already satisfied: requests-oauthlib>=0.7.0 in ./.local/lib/python3.10/site-packages (from google-auth-oauthlib==0.4.1) (2.0.0)\n",
      "Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in ./.local/lib/python3.10/site-packages (from httplib2<1dev,>=0.15.0->google-api-python-client==2.79.0) (3.1.4)\n",
      "Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in ./.local/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth==2.16.1) (0.6.1)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /opt/tljh/user/lib/python3.10/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core==2.11.0) (3.1.0)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /opt/tljh/user/lib/python3.10/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core==2.11.0) (3.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/tljh/user/lib/python3.10/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core==2.11.0) (1.26.15)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /opt/tljh/user/lib/python3.10/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core==2.11.0) (2024.6.2)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in /opt/tljh/user/lib/python3.10/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib==0.4.1) (3.2.2)\n",
      "Using cached google_auth_oauthlib-0.4.1-py2.py3-none-any.whl (18 kB)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mInstalling collected packages: google-auth-oauthlib\n",
      "  Attempting uninstall: google-auth-oauthlib\n",
      "    Found existing installation: google-auth-oauthlib 1.2.1\n",
      "    Uninstalling google-auth-oauthlib-1.2.1:\n",
      "      Successfully uninstalled google-auth-oauthlib-1.2.1\n",
      "\u001b[33m  WARNING: The script google-oauthlib-tool is installed in '/home/j-j11a303/.local/bin' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mSuccessfully installed google-auth-oauthlib-0.4.1\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: google-auth-oauthlib in ./.local/lib/python3.10/site-packages (0.4.1)\n",
      "Collecting google-auth-oauthlib\n",
      "  Using cached google_auth_oauthlib-1.2.1-py2.py3-none-any.whl.metadata (2.7 kB)\n",
      "Requirement already satisfied: google-auth>=2.15.0 in ./.local/lib/python3.10/site-packages (from google-auth-oauthlib) (2.16.1)\n",
      "Requirement already satisfied: requests-oauthlib>=0.7.0 in ./.local/lib/python3.10/site-packages (from google-auth-oauthlib) (2.0.0)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in ./.local/lib/python3.10/site-packages (from google-auth>=2.15.0->google-auth-oauthlib) (5.5.0)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in ./.local/lib/python3.10/site-packages (from google-auth>=2.15.0->google-auth-oauthlib) (0.4.1)\n",
      "Requirement already satisfied: six>=1.9.0 in /opt/tljh/user/lib/python3.10/site-packages (from google-auth>=2.15.0->google-auth-oauthlib) (1.16.0)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in ./.local/lib/python3.10/site-packages (from google-auth>=2.15.0->google-auth-oauthlib) (4.9)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in /opt/tljh/user/lib/python3.10/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib) (3.2.2)\n",
      "Requirement already satisfied: requests>=2.0.0 in /opt/tljh/user/lib/python3.10/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib) (2.32.3)\n",
      "Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in ./.local/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-auth-oauthlib) (0.6.1)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /opt/tljh/user/lib/python3.10/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib) (3.1.0)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /opt/tljh/user/lib/python3.10/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib) (3.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/tljh/user/lib/python3.10/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib) (1.26.15)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /opt/tljh/user/lib/python3.10/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib) (2024.6.2)\n",
      "Using cached google_auth_oauthlib-1.2.1-py2.py3-none-any.whl (24 kB)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mInstalling collected packages: google-auth-oauthlib\n",
      "  Attempting uninstall: google-auth-oauthlib\n",
      "    Found existing installation: google-auth-oauthlib 0.4.1\n",
      "    Uninstalling google-auth-oauthlib-0.4.1:\n",
      "      Successfully uninstalled google-auth-oauthlib-0.4.1\n",
      "\u001b[33m  WARNING: The script google-oauthlib-tool is installed in '/home/j-j11a303/.local/bin' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mSuccessfully installed google-auth-oauthlib-1.2.1\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: requests in /opt/tljh/user/lib/python3.10/site-packages (2.32.3)\n",
      "Requirement already satisfied: google-auth-oauthlib in ./.local/lib/python3.10/site-packages (1.2.1)\n",
      "Requirement already satisfied: google-auth-httplib2 in ./.local/lib/python3.10/site-packages (0.1.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /opt/tljh/user/lib/python3.10/site-packages (from requests) (3.1.0)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /opt/tljh/user/lib/python3.10/site-packages (from requests) (3.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/tljh/user/lib/python3.10/site-packages (from requests) (1.26.15)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /opt/tljh/user/lib/python3.10/site-packages (from requests) (2024.6.2)\n",
      "Requirement already satisfied: google-auth>=2.15.0 in ./.local/lib/python3.10/site-packages (from google-auth-oauthlib) (2.16.1)\n",
      "Requirement already satisfied: requests-oauthlib>=0.7.0 in ./.local/lib/python3.10/site-packages (from google-auth-oauthlib) (2.0.0)\n",
      "Requirement already satisfied: httplib2>=0.15.0 in ./.local/lib/python3.10/site-packages (from google-auth-httplib2) (0.22.0)\n",
      "Requirement already satisfied: six in /opt/tljh/user/lib/python3.10/site-packages (from google-auth-httplib2) (1.16.0)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in ./.local/lib/python3.10/site-packages (from google-auth>=2.15.0->google-auth-oauthlib) (5.5.0)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in ./.local/lib/python3.10/site-packages (from google-auth>=2.15.0->google-auth-oauthlib) (0.4.1)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in ./.local/lib/python3.10/site-packages (from google-auth>=2.15.0->google-auth-oauthlib) (4.9)\n",
      "Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in ./.local/lib/python3.10/site-packages (from httplib2>=0.15.0->google-auth-httplib2) (3.1.4)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in /opt/tljh/user/lib/python3.10/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib) (3.2.2)\n",
      "Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in ./.local/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-auth-oauthlib) (0.6.1)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m"
     ]
    }
   ],
   "source": [
    "!pip install PyDrive\n",
    "# pip install torch torchvision torchaudio\n",
    "# !pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118\n",
    "# !pip install torchvision --upgrade --index-url https://download.pytorch.org/whl/cu118\n",
    "# !pip install --upgrade torchvision --index-url https://download.pytorch.org/whl/cu118\n",
    "!pip install --force-reinstall torch torchvision --index-url https://download.pytorch.org/whl/cu118\n",
    "!pip install opencv-python\n",
    "!pip install opencv-python-headless\n",
    "!pip install torchvision\n",
    "!pip install google-api-core==2.11.0 google-api-python-client==2.79.0 google-auth==2.16.1 google-auth-httplib2==0.1.0 google-auth-oauthlib==0.4.1 googleapis-common-protos==1.58.0\n",
    "!pip install --upgrade google-auth-oauthlib\n",
    "!pip install requests google-auth-oauthlib google-auth-httplib2\n",
    "# !pip install --force-reinstall sympy\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "db2eb597-abd6-48b2-ac16-ac05ddbeaebc",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: tqdm in /opt/tljh/user/lib/python3.10/site-packages (4.65.0)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: ultralytics in ./.local/lib/python3.10/site-packages (8.2.100)\n",
      "Requirement already satisfied: numpy<2.0.0,>=1.23.0 in ./.local/lib/python3.10/site-packages (from ultralytics) (1.26.3)\n",
      "Requirement already satisfied: matplotlib>=3.3.0 in ./.local/lib/python3.10/site-packages (from ultralytics) (3.9.2)\n",
      "Requirement already satisfied: opencv-python>=4.6.0 in ./.local/lib/python3.10/site-packages (from ultralytics) (4.10.0.84)\n",
      "Requirement already satisfied: pillow>=7.1.2 in ./.local/lib/python3.10/site-packages (from ultralytics) (10.2.0)\n",
      "Requirement already satisfied: pyyaml>=5.3.1 in /opt/tljh/user/lib/python3.10/site-packages (from ultralytics) (6.0.1)\n",
      "Requirement already satisfied: requests>=2.23.0 in /opt/tljh/user/lib/python3.10/site-packages (from ultralytics) (2.32.3)\n",
      "Requirement already satisfied: scipy>=1.4.1 in ./.local/lib/python3.10/site-packages (from ultralytics) (1.14.1)\n",
      "Requirement already satisfied: torch>=1.8.0 in ./.local/lib/python3.10/site-packages (from ultralytics) (2.4.1+cu118)\n",
      "Requirement already satisfied: torchvision>=0.9.0 in ./.local/lib/python3.10/site-packages (from ultralytics) (0.19.1+cu118)\n",
      "Requirement already satisfied: tqdm>=4.64.0 in /opt/tljh/user/lib/python3.10/site-packages (from ultralytics) (4.65.0)\n",
      "Requirement already satisfied: psutil in /opt/tljh/user/lib/python3.10/site-packages (from ultralytics) (5.9.8)\n",
      "Requirement already satisfied: py-cpuinfo in ./.local/lib/python3.10/site-packages (from ultralytics) (9.0.0)\n",
      "Requirement already satisfied: pandas>=1.1.4 in ./.local/lib/python3.10/site-packages (from ultralytics) (2.2.3)\n",
      "Requirement already satisfied: seaborn>=0.11.0 in ./.local/lib/python3.10/site-packages (from ultralytics) (0.13.2)\n",
      "Requirement already satisfied: ultralytics-thop>=2.0.0 in ./.local/lib/python3.10/site-packages (from ultralytics) (2.0.8)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in ./.local/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics) (1.3.0)\n",
      "Requirement already satisfied: cycler>=0.10 in ./.local/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in ./.local/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics) (4.54.0)\n",
      "Requirement already satisfied: kiwisolver>=1.3.1 in ./.local/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics) (1.4.7)\n",
      "Requirement already satisfied: packaging>=20.0 in /opt/tljh/user/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics) (24.0)\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in ./.local/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics) (3.1.4)\n",
      "Requirement already satisfied: python-dateutil>=2.7 in /opt/tljh/user/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in ./.local/lib/python3.10/site-packages (from pandas>=1.1.4->ultralytics) (2024.2)\n",
      "Requirement already satisfied: tzdata>=2022.7 in ./.local/lib/python3.10/site-packages (from pandas>=1.1.4->ultralytics) (2024.2)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /opt/tljh/user/lib/python3.10/site-packages (from requests>=2.23.0->ultralytics) (3.1.0)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /opt/tljh/user/lib/python3.10/site-packages (from requests>=2.23.0->ultralytics) (3.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/tljh/user/lib/python3.10/site-packages (from requests>=2.23.0->ultralytics) (1.26.15)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /opt/tljh/user/lib/python3.10/site-packages (from requests>=2.23.0->ultralytics) (2024.6.2)\n",
      "Requirement already satisfied: filelock in ./.local/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (3.13.1)\n",
      "Requirement already satisfied: typing-extensions>=4.8.0 in ./.local/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (4.9.0)\n",
      "Requirement already satisfied: sympy in ./.local/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (1.12)\n",
      "Requirement already satisfied: networkx in ./.local/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (3.2.1)\n",
      "Requirement already satisfied: jinja2 in ./.local/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (3.1.3)\n",
      "Requirement already satisfied: fsspec in ./.local/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (2024.2.0)\n",
      "Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.8.89 in ./.local/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (11.8.89)\n",
      "Requirement already satisfied: nvidia-cuda-runtime-cu11==11.8.89 in ./.local/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (11.8.89)\n",
      "Requirement already satisfied: nvidia-cuda-cupti-cu11==11.8.87 in ./.local/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (11.8.87)\n",
      "Requirement already satisfied: nvidia-cudnn-cu11==9.1.0.70 in ./.local/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (9.1.0.70)\n",
      "Requirement already satisfied: nvidia-cublas-cu11==11.11.3.6 in ./.local/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (11.11.3.6)\n",
      "Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in ./.local/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (10.9.0.58)\n",
      "Requirement already satisfied: nvidia-curand-cu11==10.3.0.86 in ./.local/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (10.3.0.86)\n",
      "Requirement already satisfied: nvidia-cusolver-cu11==11.4.1.48 in ./.local/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (11.4.1.48)\n",
      "Requirement already satisfied: nvidia-cusparse-cu11==11.7.5.86 in ./.local/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (11.7.5.86)\n",
      "Requirement already satisfied: nvidia-nccl-cu11==2.20.5 in ./.local/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (2.20.5)\n",
      "Requirement already satisfied: nvidia-nvtx-cu11==11.8.86 in ./.local/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (11.8.86)\n",
      "Requirement already satisfied: triton==3.0.0 in ./.local/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (3.0.0)\n",
      "Requirement already satisfied: six>=1.5 in /opt/tljh/user/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.16.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in ./.local/lib/python3.10/site-packages (from jinja2->torch>=1.8.0->ultralytics) (2.1.5)\n",
      "Requirement already satisfied: mpmath>=0.19 in ./.local/lib/python3.10/site-packages (from sympy->torch>=1.8.0->ultralytics) (1.3.0)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m"
     ]
    }
   ],
   "source": [
    "# YOLOv8 모델  설치\n",
    "!pip3 install tqdm\n",
    "!pip install ultralytics"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "7c37823c-fbaa-4971-89e8-b740f1308e5b",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 라이브러리 불러오기\n",
    "import os\n",
    "import time\n",
    "import pickle\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 66,
   "id": "23849517-8b6f-4e1a-9f4f-3c9709ab407d",
   "metadata": {},
   "outputs": [],
   "source": [
    "## 토큰이 만료되었을 경우!!!\n",
    "from apiclient import discovery\n",
    "from httplib2 import Http\n",
    "import oauth2client\n",
    "from oauth2client import file, client, tools\n",
    "\n",
    "obj = lambda: None\n",
    "\n",
    "# OAuth 2.0 설정을 위한 딕셔너리\n",
    "lmao = {\"auth_host_name\":'localhost', 'noauth_local_webserver':'store_true', 'auth_host_port':[8080, 8090], 'logging_level':'ERROR'}\n",
    "for k, v in lmao.items():\n",
    "    setattr(obj, k, v)\n",
    "    \n",
    "# OAuth 2.0 인증을 위한 설정\n",
    "SCOPES = 'https://www.googleapis.com/auth/drive.readonly'\n",
    "store = file.Storage('token.json')\n",
    "creds = store.get()\n",
    "# The following will give you a link if token.json does not exist, the link allows the user to give this app permission\n",
    "if not creds or creds.invalid:\n",
    "    flow = client.flow_from_clientsecrets('client_secrets.json', SCOPES)\n",
    "    creds = tools.run_flow(flow, store, obj)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ae3b17ea-aa63-40d0-98a6-15c054e35c99",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Google Drive API를 사용하여 인증 관리\n",
    "from pydrive.auth import GoogleAuth\n",
    "from pydrive.drive import GoogleDrive\n",
    "# Google OAuth 인증 절차\n",
    "gauth = GoogleAuth()\n",
    "\n",
    "\n",
    "# 이미 저장된 자격 증명 파일이 있으면 로드\n",
    "if os.path.exists(\"credentials.json\"):\n",
    "    gauth.LoadCredentialsFile(\"credentials.json\")\n",
    "    if gauth.access_token_expired:  # 토큰이 만료되었으면 갱신\n",
    "        print(\"토큰 만료로 갱신\")\n",
    "        gauth.Refresh()\n",
    "    else:  # 유효한 토큰이 있으면 인증 절차 건너뜀\n",
    "        print(\"토큰이 있어 패스\")\n",
    "        gauth.Authorize()\n",
    "else:\n",
    "    # 자격 증명 파일이 없으면 새로 인증\n",
    "    gauth.CommandLineAuth() # 이 과정을 통해 브라우저가 열리고, Google 계정 인증이 이루어짐\n",
    "    gauth.SaveCredentialsFile(\"credentials.json\")  # 자격 증명 파일 저장\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "f820e38e-010a-4999-9573-e54a34691598",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Google Drive 객체 생성\n",
    "drive = GoogleDrive(gauth)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b95cccbb-cf1f-4c40-93db-9eb0b2786324",
   "metadata": {},
   "source": [
    "## Drive에서 파일을 불러와 딕셔너리에 저장"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9da63e83-fb6f-4305-8179-a5c447f54d88",
   "metadata": {},
   "source": [
    "### 하위 폴더까지 탐색하는 코드"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "27e84caf-88f5-41d5-94b5-a77d753ade47",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 재귀적으로 폴더 탐색하여 파일 목록 가져오기\n",
    "def recursive_list_files(drive, folder_id):\n",
    "    files = []\n",
    "    print(f\"폴더 탐색 중: {folder_id}\")  # 폴더 ID 출력\n",
    "    # 현재 폴더 내 파일 및 폴더 목록 가져오기\n",
    "    file_list = drive.ListFile({'q': f\"'{folder_id}' in parents and trashed=false\"}).GetList()\n",
    "\n",
    "    for file in file_list:\n",
    "        if file['mimeType'] == 'application/vnd.google-apps.folder':  # 폴더인 경우 재귀 호출\n",
    "            files.extend(recursive_list_files(drive, file['id']))\n",
    "        else:\n",
    "            files.append(file)\n",
    "    return files"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "956a3679-de79-4c97-980b-25d90639d144",
   "metadata": {},
   "source": [
    "### Drive API 호출 시 에러가 발생하면 일정 시간 대기 후 재시도"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "c3cb49dc-06b3-41c5-80cb-dc9c304e2d27",
   "metadata": {},
   "outputs": [],
   "source": [
    "from googleapiclient.errors import HttpError\n",
    "\n",
    "# Google Drive API 호출 시 에러가 발생하면 일정 시간 대기 후 재시도\n",
    "def drive_list_files_with_retry(drive, folder_id, retries=10, wait_time=5):\n",
    "    try:\n",
    "        return drive.ListFile({'q': f\"'{folder_id}' in parents and trashed=false\", 'maxResults': 400}).GetList()\n",
    "    except HttpError as error:\n",
    "        if retries > 0:\n",
    "            print(f\"HttpError 발생: {error}. {wait_time}초 후 재시도합니다... 남은 재시도 횟수: {retries}\")\n",
    "            time.sleep(wait_time)\n",
    "            return drive_list_files_with_retry(drive, folder_id, retries-1, wait_time*1.5 )  # 대기 시간 증가\n",
    "        else:\n",
    "            print(f\"HttpError 발생: {error}. 재시도 횟수 초과.\")\n",
    "            raise error\n",
    "\n",
    "# 캐시 파일 경로 설정\n",
    "label_cache_file = 'lane_label_files.pkl'\n",
    "\n",
    "# 캐시 파일에서 데이터 불러오기\n",
    "def load_cached_files(cache_file):\n",
    "    if os.path.exists(cache_file):\n",
    "        print('캐시 파일에서 데이터 불러오기...')\n",
    "        with open(cache_file, 'rb') as f:\n",
    "            return pickle.load(f)\n",
    "    return None\n",
    "\n",
    "# 캐시 파일 저장하기\n",
    "def save_cached_files(files, cache_file):\n",
    "    current_time = time.strftime(\"%Y-%m-%d %H:%M:%S\", time.localtime())  # 현재 시간 포맷\n",
    "\n",
    "    with open(cache_file, 'wb') as f:\n",
    "        pickle.dump(files, f)\n",
    "        print(f\"[{current_time}] 캐시 저장 완료. 현재까지 탐색된 파일 수: {len(files)}\")\n",
    "\n",
    "\n",
    "# 재귀적으로 폴더 탐색하여 파일 목록 가져오기\n",
    "def recursive_list_files(drive, folder_id, cache_file, files=None, save_interval=500):\n",
    "    if files is None:\n",
    "        files = load_cached_files(cache_file)\n",
    "        \n",
    "    print(f\"폴더 탐색 중: {folder_id}\")  # 폴더 ID 출력\n",
    "    \n",
    "    # 현재 폴더 내 파일 및 폴더 목록 가져오기\n",
    "    file_list = drive_list_files_with_retry(drive, folder_id)\n",
    "    # file_list = drive.ListFile({'q': f\"'{folder_id}' in parents and trashed=false\"}).GetList()\n",
    "\n",
    "    for file in file_list:\n",
    "        if file['mimeType'] == 'application/vnd.google-apps.folder':  # 폴더인 경우 재귀 호출\n",
    "            files = recursive_list_files(drive, file['id'],cache_file, files, save_interval)\n",
    "        else:\n",
    "            files.append(file)\n",
    "\n",
    "        # 일정 간격(save_interval)마다 캐시 파일로 저장\n",
    "        if len(files) % save_interval == 0:\n",
    "            save_cached_files(files,cache_file)\n",
    "\n",
    "    return files"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6fde8b3f-19db-46ae-868c-e7a5fa525b77",
   "metadata": {},
   "source": [
    "### 라벨 데이터 캐싱 + 딕셔너리에 저장하는 코드"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3b855cf9-d302-445a-b59f-2ac76b849262",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "# 캐싱을 이용하여 가져온 파일 목록을 로컬로 저장하고, 저장된걸 불러오는 방식\n",
    "\n",
    "\n",
    "start_time = time.time()\n",
    "\n",
    "# 라벨 및 원천 데이터의 최상위 폴더 ID\n",
    "training_folder_id = '15KO-jwlD4JFxWO2vcODvl89qg_qmgHIp'\n",
    "\n",
    "\n",
    "# 캐시 파일 경로 설정\n",
    "label_cache_file = 'lane_label_files.pkl'\n",
    "\n",
    "\n",
    "\n",
    "# Google Drive에서 가져온 폴더 ID 예시\n",
    "label_folder_id = '15aPJnLjR2vJ3okuPT5Vl-Ynf41M7Dikn'  # 라벨링 데이터 폴더 ID를 수동으로 설정 \n",
    "\n",
    "# # 캐시 파일이 있는지 확인하고 불러오기\n",
    "# if os.path.exists(label_cache_file):\n",
    "#     print('캐시 파일에서 라벨 데이터 불러오기...')\n",
    "#     with open(label_cache_file, 'rb') as f:\n",
    "#         label_files = pickle.load(f)\n",
    "# else:\n",
    "#     print('캐시 파일이 없습니다. Google Drive에서 파일 목록 가져오기...')\n",
    "\n",
    "# 캐시 파일이 있는지 확인하고 불러오기\n",
    "label_files = load_cached_files(label_cache_file)\n",
    "\n",
    "# if len(label_files) == 0:\n",
    "#     print('캐시 파일이 없습니다. Google Drive에서 파일 목록 가져오기...')\n",
    "\n",
    "if label_folder_id:\n",
    "    # 라벨 파일 가져오기\n",
    "    print('라벨쪽 실행시작...')\n",
    "    label_files = recursive_list_files(drive, label_folder_id, label_cache_file)\n",
    "    print(f\"라벨 파일 수: {len(label_files)}\")\n",
    "\n",
    "    # 파일 목록을 캐시 파일에 저장\n",
    "    save_cached_files(label_files, label_cache_file)\n",
    "else:\n",
    "    print(\"라벨 폴더의 ID를 찾을 수 없습니다.\")\n",
    "    label_files = []\n",
    "\n",
    "\n",
    "    # if label_folder_id:\n",
    "\n",
    "    #     # 라벨 파일 가져오기\n",
    "    #     print('라벨쪽 실행시작...')\n",
    "    #     label_files = recursive_list_files(drive, label_folder_id, label_cache_file)\n",
    "    #     print(f\"라벨 파일 수: {len(label_files)}\")\n",
    "\n",
    "\n",
    "\n",
    "    #     # 파일 목록을 캐시 파일에 저장\n",
    "    #     save_cached_files(label_files, label_cache_file)\n",
    "    # else:\n",
    "    #     print(\"라벨 폴더의 ID를 찾을 수 없습니다.\")\n",
    "    #     label_files = []\n",
    "\n",
    "# 캐시된 데이터에서 딕셔너리 생성\n",
    "label_dict = {file['title']: file['id'] for file in label_files if file['title'].endswith('.json')}\n",
    "\n",
    "\n",
    "# 라벨 파일 목록 일부 출력\n",
    "print(\"라벨 파일 목록 일부:\", list(label_dict.items())[:5])\n",
    "\n",
    "# 실행 종료 시간 기록\n",
    "end_time = time.time()\n",
    "# 실행 시간 계산 및 출력\n",
    "execution_time = end_time - start_time\n",
    "print(f\"코드 실행 시간: {execution_time:.2f}초\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "38826398-38cf-4f96-9898-7a00fa3d55f0",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"라벨 파일 목록 일부:\", list(label_dict.items())[60690:])\n",
    "print(len(label_dict))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5d664c88-1a31-4c40-8633-a2a70475320e",
   "metadata": {},
   "source": [
    "### 원천 데이터 캐싱 + 딕셔너리에 저장하는 코드"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d0663594-d746-442b-85c7-e32e8dffb3e0",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 캐싱을 이용하여 가져온 파일 목록을 로컬로 저장하고, 저장된걸 불러오는 방식\n",
    "\n",
    "\n",
    "start_time = time.time()\n",
    "\n",
    "# 라벨 및 원천 데이터의 최상위 폴더 ID\n",
    "training_folder_id = '15KO-jwlD4JFxWO2vcODvl89qg_qmgHIp'\n",
    "\n",
    "# 캐시 파일 경로 설정\n",
    "image_cache_file = 'lane_image_files.pkl'\n",
    "\n",
    "# Google Drive에서 가져온 폴더 ID\n",
    "iamge_folder_id = '16SWhdIvoJ7ExlXLMUZkZL1E0qxJHEMTj'  # 원천 데이터 폴더 ID를 수동으로 설정 \n",
    "\n",
    "\n",
    "# 캐시 파일이 있는지 확인하고 불러오기\n",
    "iamge_files = load_cached_files(iamge_folder_id)\n",
    "\n",
    "if iamge_folder_id:\n",
    "    # 원천 파일 가져오기\n",
    "    print('원천쪽 실행시작...')\n",
    "    iamge_files = recursive_list_files(drive, iamge_folder_id, iamge_cache_file)\n",
    "    print(f\"사진 파일 수: {len(iamge_files)}\")\n",
    "\n",
    "    # 파일 목록을 캐시 파일에 저장\n",
    "    save_cached_files(iamge_files, iamge_cache_file)\n",
    "else:\n",
    "    print(\"이미지 폴더의 ID를 찾을 수 없습니다.\")\n",
    "    image_files = []\n",
    "\n",
    "\n",
    "# 캐시된 데이터에서 딕셔너리 생성\n",
    "image_dict = {file['title']: file['id'] for file in image_files if file['title'].endswith('.jpg')}\n",
    "\n",
    "print(\"이미지 파일 목록 일부:\", list(image_dict.items())[:5])\n",
    "\n",
    "# 실행 종료 시간 기록\n",
    "end_time = time.time()\n",
    "# 실행 시간 계산 및 출력\n",
    "execution_time = end_time - start_time\n",
    "print(f\"코드 실행 시간: {execution_time:.2f}초\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d664ce94-1670-4c18-8c57-e7e90b24c174",
   "metadata": {},
   "outputs": [],
   "source": [
    "# # 라벨과 원천 한 번에 처리하는 코드\n",
    "# # 캐싱을 이용하여 가져온 파일 목록을 로컬로 저장하고, 저장된걸 불러오는 방식\n",
    "\n",
    "\n",
    "# start_time = time.time()\n",
    "\n",
    "# # 라벨 및 원천 데이터의 최상위 폴더 ID\n",
    "# training_folder_id = '15KO-jwlD4JFxWO2vcODvl89qg_qmgHIp'\n",
    "\n",
    "\n",
    "# # 캐시 파일 경로 설정\n",
    "# label_cache_file = 'lane_label_files.pkl'\n",
    "# image_cache_file = 'lane_image_files.pkl'\n",
    "\n",
    "\n",
    "# # Google Drive에서 가져온 폴더 ID 예시\n",
    "# label_folder_id = '15aPJnLjR2vJ3okuPT5Vl-Ynf41M7Dikn'  # 라벨링 데이터 폴더 ID를 수동으로 설정 \n",
    "# source_folder_id = '16SWhdIvoJ7ExlXLMUZkZL1E0qxJHEMTj'  # 원천 데이터 폴더 ID를 수동으로 설정 \n",
    "\n",
    "# # 캐시 파일이 있는지 확인하고 불러오기\n",
    "# if os.path.exists(label_cache_file) and os.path.exists(image_cache_file):\n",
    "#     print('캐시 파일에서 데이터 불러오기...')\n",
    "#     with open(label_cache_file, 'rb') as f:\n",
    "#         label_files = pickle.load(f)\n",
    "#     with open(image_cache_file, 'rb') as f:\n",
    "#         image_files = pickle.load(f)\n",
    "# else:\n",
    "#     print('캐시 파일이 없습니다. Google Drive에서 파일 목록 가져오기...')\n",
    "\n",
    "\n",
    "#     if label_folder_id and source_folder_id:\n",
    "\n",
    "#         # 라벨 파일 가져오기\n",
    "#         print('라벨쪽 실행시작...')\n",
    "#         label_files = recursive_list_files(drive, label_folder_id)\n",
    "#         print(f\"라벨 파일 수: {len(label_files)}\")\n",
    "\n",
    "#         # 원천 파일 가져오기\n",
    "#         print('원천 데이터 가져오기 시작...')\n",
    "#         image_files = recursive_list_files(drive, source_folder_id)\n",
    "#         print(f\"이미지 파일 수: {len(image_files)}\")\n",
    "\n",
    "#         # label_files = []\n",
    "#         # image_files = []\n",
    "\n",
    "#         # # 라벨 데이터 가져오기\n",
    "#         # print('라벨쪽 실행시작')\n",
    "#         # label_folders = ['A', 'B', 'C']\n",
    "#         # violation_types = ['BLUE', 'SHOULDER', 'WHITE', 'YELLOW']\n",
    "        \n",
    "#         # for folder in label_folders:\n",
    "#         #     for violation in violation_types:\n",
    "#         #         folder_path = f'라벨링데이터/TL/{folder}/{violation}'\n",
    "#         #         subfolders = drive.ListFile({'q': f\"'{label_folder_id}' in parents and trashed=false\"}).GetList()\n",
    "#         #         for subfolder in subfolders:\n",
    "#         #             files = drive.ListFile({'q': f\"'{subfolder['id']}' in parents and trashed=false\"}).GetList()\n",
    "#         #             label_files.extend(files)\n",
    "#         # print(f\"라벨 파일 수: {len(label_files)}\")  # 라벨 파일 개수 출력\n",
    "\n",
    "#         # # 원천 데이터 가져오기\n",
    "#         # print('원천 데이터 가져오기 시작...')\n",
    "#         # ts_folders = ['TS1', 'TS2', 'TS3']  # TS1, TS2, TS3 폴더\n",
    "#         # for ts in ts_folders:\n",
    "#         #     folder_path = f'원천데이터/{ts}/A'\n",
    "#         #     subfolders = drive.ListFile({'q': f\"'{source_folder_id}' in parents and trashed=false\"}).GetList()\n",
    "#         #     for subfolder in subfolders:\n",
    "#         #         files = drive.ListFile({'q': f\"'{subfolder['id']}' in parents and trashed=false\"}).GetList()\n",
    "#         #         image_files.extend(files)\n",
    "#         # print(f\"이미지 파일 수: {len(image_files)}\")  # 이미지 파일 개수 출력\n",
    "\n",
    "#         # 파일 목록을 캐시 파일에 저장\n",
    "#         with open(label_cache_file, 'wb') as f:\n",
    "#             pickle.dump(label_files, f)\n",
    "#         with open(image_cache_file, 'wb') as f:\n",
    "#             pickle.dump(image_files, f)\n",
    "#     else:\n",
    "#         print(\"라벨 또는 원천 폴더의 ID를 찾을 수 없습니다.\")\n",
    "#         label_files = []\n",
    "#         image_files = []\n",
    "\n",
    "# # 캐시된 데이터에서 딕셔너리 생성\n",
    "# label_dict = {file['title']: file['id'] for file in label_files if file['title'].endswith('.json')}\n",
    "# image_dict = {file['title']: file['id'] for file in image_files if file['title'].endswith('.jpg')}\n",
    "\n",
    "\n",
    "# # 라벨 및 이미지 파일 목록 일부 출력\n",
    "# print(\"라벨 파일 목록 일부:\", list(label_dict.items())[:5])\n",
    "# print(\"이미지 파일 목록 일부:\", list(image_dict.items())[:5])\n",
    "\n",
    "# # 실행 종료 시간 기록\n",
    "# end_time = time.time()\n",
    "# # 실행 시간 계산 및 출력\n",
    "# execution_time = end_time - start_time\n",
    "# print(f\"코드 실행 시간: {execution_time:.2f}초\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "urecar",
   "language": "python",
   "name": "urecar"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
